SELECT * FROM customer LIMIT 20;

-- Q1. What is the total revenue generated by male vs. female customers?
SELECT "Gender",
       SUM("Purchase Amount (USD)") AS revenue
FROM customer
GROUP BY "Gender";
-- Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT *
FROM customer
WHERE "Discount Applied" = 'Yes'
  AND "Purchase Amount (USD)" > (
        SELECT AVG("Purchase Amount (USD)") FROM customer
      );
	  -- Q3. Which are the top 5 products with the highest average review rating?
SELECT "Item Purchased",
       AVG("Review Rating") AS avg_rating
FROM customer
GROUP BY "Item Purchased"
ORDER BY avg_rating DESC
LIMIT 5;
-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT "Shipping Type",
       AVG("Purchase Amount (USD)") AS avg_purchase_amount
FROM customer
GROUP BY "Shipping Type";
-- Q5. Do subscribed customers spend more? 
-- Compare average spend and total revenue between subscribers and non-subscribers.
SELECT "Subscription Status",
       AVG("Purchase Amount (USD)") AS avg_spend,
       SUM("Purchase Amount (USD)") AS total_revenue
FROM customer
GROUP BY "Subscription Status";
-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT "Item Purchased",
       (SUM(CASE WHEN "Discount Applied" = 'Yes' THEN 1 ELSE 0 END) * 100.0 
        / COUNT(*)) AS discount_percentage
FROM customer
GROUP BY "Item Purchased"
ORDER BY discount_percentage DESC
LIMIT 5;
-- Q7. Segment customers into New, Returning, and Loyal based on their total
-- number of previous purchases, and show the count of each segment.

WITH customer_type AS (
    SELECT 
        "Customer ID",
        "Previous Purchases",
        CASE
            WHEN "Previous Purchases" = 1 THEN 'New'
            WHEN "Previous Purchases" BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer
)
SELECT 
    customer_segment,
    COUNT(*) AS customer_count
FROM customer_type
GROUP BY customer_segment
ORDER BY customer_segment;
-- Q8. What are the top 3 most purchased products within each category?

WITH product_counts AS (
    SELECT 
        "Category",
        "Item Purchased",
        COUNT(*) AS purchase_count,
        ROW_NUMBER() OVER (
            PARTITION BY "Category"
            ORDER BY COUNT(*) DESC
        ) AS rn
    FROM customer
    GROUP BY "Category", "Item Purchased"
)
SELECT 
    "Category",
    "Item Purchased",
    purchase_count
FROM product_counts
WHERE rn <= 3
ORDER BY "Category", purchase_count DESC;
-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT "Subscription Status",
       COUNT(*) AS customer_count
FROM customer
WHERE "Previous Purchases" > 5
GROUP BY "Subscription Status"
ORDER BY "Subscription Status";
-- Q10. What is the revenue contribution of each age group?

UPDATE customer
SET age_group =
    CASE
        WHEN "Age" BETWEEN 18 AND 29 THEN 'Young Adult'
        WHEN "Age" BETWEEN 30 AND 45 THEN 'Adult'
        WHEN "Age" BETWEEN 46 AND 60 THEN 'Middle-aged'
        ELSE 'Senior'
    END;
	SELECT age_group,
       SUM("Purchase Amount (USD)") AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;









